"""fix order columns

Revision ID: de33ab18d233
Revises: 52e408cdab37
Create Date: 2026-07-08 14:07:30.182710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de33ab18d233'
down_revision = '52e408cdab37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('stripe_payment_intent_id')
        batch_op.drop_column('delivery_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))
        batch_op.add_column(sa.Column('stripe_payment_intent_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('payment_id')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
